@baseUrl=https://localhost:7133
@applicationId=test-app

### Create a patient
POST {{baseUrl}}/Patient
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
    "resourceType": "Patient",
    "identifier": [
        {
            "system": "http://ihis.sg/identifier/nric",
            "value": "S1500008B"
        }
    ],
    "active": false,
    "name": [
        {
            "text": "Resident 03"
        }
    ],
    "gender": "male",
    "birthDate": "1977-12-09"
}

### Create a patient with canned patch-extended operation
POST {{baseUrl}}/Patient/$create-partial
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "nric",
            "valueString": "S2900005B"
        },
        {
            "name": "name",
            "valueString": "Serena"
        }
    ]
}

### Create a patient with canned create operation
POST {{baseUrl}}/Patient/$create-full
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
    "resourceType": "Patient",
    "identifier": [
        {
            "system": "http://ihis.sg/identifier/nric",
            "value": "S1900005B"
        }
    ],
    "active": true,
    "name": [
        {
            "text": "Resident 03"
        }
    ],
    "gender": "male",
    "birthDate": "1977-12-09"
}

### Search patient with canned create search operation
POST {{baseUrl}}/Patient/$search
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "nric",
            "valueString": "S1900009B"
        }
    ]
}

### Retrieve a patient with canned get operation
POST {{baseUrl}}/Patient/$retrieve
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "identifier",
            "valueString": "S1900009B"
        }
    ]
}


### Update a patient with canned patch-extended operation and pre-patch profile
POST {{baseUrl}}/Patient/$update
X-Ihis-SourceApplication: {{applicationId}}
Content-Type: application/fhir+json

{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "nric",
            "valueString": "S1500008B"
        },
        {
            "name": "DOB",
            "valueDate": "2000-01-19"
        }
    ]
}
